# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# test
name: Java CI with Maven and CD docker

on:
  workflow_dispatch:
  push:
    branches: [ developer]
  pull_request:
    branches: [ main ]
    on: workflow_dispatch
permissions:
        id-token: write
        contents: read

jobs:
   
  Build:
    name: build and test
    runs-on: ubuntu-latest
    env:
      env-file: my-environment-file.env 

    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 18
       uses: actions/setup-java@v1
       with:
         java-version: 18
     - name: Build with Maven
       run: mvn -B clean package
     - name: Archive jar file
       uses: actions/upload-artifact@v2
       with:
         name: myjar
         path: target/ppu-1.0-SNAPSHOT.jar

  Docker: 
 
    name: build image and publish
    needs: Build
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }}
          -p ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
         java-version: 18
      - name: Build with Maven
        run: mvn -B clean package
        
      - name: Build Docker image
        run: docker build -t hajaraburmeileh/hello:latestt .
      - name: Publish Docker image
        run: docker push hajaraburmeileh/hello